### ISSUE TITLE
Updates not realtime

### ISSUE THREAD

**Issue by adamstortz** [Microsoft/ngconf2015demo#7]
When data is changed in one user session, it is not reflected in others until a key is hit or one of the todo items is checked.  I am wondering where the issue lies.  Is it Angular2, AngularFire, or this particular demo?

Example, if the view is in this state, the screen on the left is out of date until I hit the A key and then the two are in sync:
![screenshot 2015-03-07 15 16 23](https://cloud.githubusercontent.com/assets/5168605/6543313/136c1f7e-c4dd-11e4-82df-7c8cba5bf526.png)
![screenshot 2015-03-07 15 16 44](https://cloud.githubusercontent.com/assets/5168605/6543316/1694996a-c4dd-11e4-8f2a-8fe40480d47e.png)

**Comment by davideast** [comment]
This is due to the old version of Zone.js. This issue is fixed in the latest version.

**Comment by adamstortz** [comment]
I have upgraded to the latest version of Zone.js and that has not fixed the issue.  I have also pulled down the latest source from this repo and it is still happening.
